### ISSUE TITLE
Failure running syslog_create.py

### ISSUE THREAD

**Issue by DerWolf11** [brocade/pyfos#10]
Hello dev team,

I am trying to run the syslog_create.py main included in the latest repo util directory, have provided all of the required parameters outlined by the help and documentation, but I am getting a failure asking to "Please provide the missing util script option."

My parameters (dummy values inserted):
-i 1.2.3.4 -L admin -P password --server=10.11.12.13 --port=514 --secure-mode=False

Do you see any obvious missing parameters that would cause this failure?

Also noticed that the code is setting the filter to **secure_mode** while other areas of the code are using **secure-mode**. 

syslog_create.py (line: 124)
filters = ['server', 'port', 'secure_mode']

OS: Windows 2012
Python version: 3.6

**Comment by daniel-chung-broadcom** [comment]
If secure-mode is false, there is no need to give port. It is taking a default port number internally. The help output will be updated in the next release to clarify the usage.

**Comment by DerWolf11** [comment]
Your suggestion worked perfectly. Thank you very much for your help!
