### ISSUE TITLE
Login Issue (Unknown login error)

### ISSUE THREAD

**Issue by rahulmahendru** [brocade/pyfos#11]
I just installed the module and it looks really helpful. I am trying to login to a brocade REST OS and i keep getting an error which says unknown login error. The rest_util replies with Incorrect auth detail. I am able to establish a connection using paramiko and using regular ssh. Please help

**Comment by jconsoli** [comment]
Sorry for the delay in responding. The community board is better monitored. Go to https://community.broadcom.com/home, create a user account if you don't already have one, and join the fibre channel automation community.

We would need to see the exact error message and response code to provide additional assistance.

**Comment by rahulmahendru** [comment]
Thank you for reaching out. I found a solution to the error I was facing. Ill use the link for future issues.
